[package]
name = "project-guard"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
colored = "3.1.1"
indicatif = "0.18.6"
md-5 = "0.11.0"
notify = "8.2.0"
object = "0.40.0"
reqwest = { version = "0.13.5", features = ["json", "blocking"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
walkdir = "2.5.0"
yara-x = "1.20.0"
regex = "1.11"
base64 = "0.22"

[build-dependencies]
winres = "0.1"
